export const IconsPath = {
  GPT: "/icons/gpt.svg",
  PainTrack: "/icons/pain-track.svg",
  GPTBlack: "/icons/gpt-black.svg",
  DoctorBlack: "/icons/doctor-black.svg",
  Doctor: "/icons/doctor.svg",
  Patient: "/icons/patient.svg",
  Episode: "/icons/episode.svg",
  texture: {
    Stretching: "/texture/stretching.svg",
    Stinging: "/texture/stinging.svg",
    Burning: "/texture/burning.svg",
    Pressing: "/texture/pressing.svg",
  },
  depth: {
    Muscular: "/depth/muscular.svg",
    Bone: "/depth/bone.svg",
    Superficial: "/depth/superficial.svg",
    Visceral: "/depth/visceral.svg",
    Anatomy: "/depth/anatomy.svg",
  },
  Invervention: "/icons/intervention.svg",
  Symptom: "/icons/symptom.svg",
  Publish: "/icons/pub.svg",
};
