export const IconsPath = {
  GPT: "/icons/gpt.svg",
  PainTrack: "/icons/pain-track-logo.svg",
  Burger: "/icons/burger.svg",
  GPTBlack: "/icons/gpt-black.svg",
  DoctorBlack: "/icons/doctor-black.svg",
  Doctor: "/icons/doctor.svg",
  Patient: "/icons/patient.svg",
  Animal: "/icons/animal.svg",
  Episode: "/icons/episode.svg",
  texture: {
    stretching: "/texture/stretching.svg",
    stinging: "/texture/stinging.svg",
    burning: "/texture/burning.svg",
    pressing: "/texture/pressing.svg",
  },
  depth: {
    muscular: "/depth/muscular.svg",
    bone: "/depth/bone.svg",
    superficial: "/depth/superficial.svg",
    visceral: "/depth/visceral.svg",
    anatomy: "/depth/anatomy.svg",
  },
  Invervention: "/icons/intervention.svg",
  Symptom: "/icons/symptom.svg",
  Publish: "/icons/pub.svg",
  PubMain: "/icons/pub-main.svg",
  Syncing: "/icons/syncing.svg",
  Synced: "/icons/synced.svg",
  Unavailable: "/icons/unavailable.svg",
  Web: "/icons/web.svg",
  Linkedin: "/icons/linkedin.svg",
  Mail: "/icons/mail.svg",
};

export const ImagesPath = {
  WelfareLogo: "/images/welfare-logo.png",
  DoctorIllustration: "/assets/doctor.svg",
  OkBro: "/assets/ok-bro.svg",
  VetIllustration: "/assets/vet.svg",
  MailSentBro: "/assets/mail-sent-bro.png",
  PieceOfMindoBro: "/assets/piece-of-mind-bro.png",
};
