const SIZE_MULTIPLIER = 1.5;

export const SEGMENT_WIDTH = 120 * SIZE_MULTIPLIER;

export const SEGMENT_SECTION_HEIGHT = 42 * SIZE_MULTIPLIER;

export const SEGMENT_HEIGHT = SEGMENT_SECTION_HEIGHT * 5;
